import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const cook = await cookies();
  const lastPath = cook.get('lastPath')?.value;

  if (session?.user) {
    if (session.user.isOnboard) {
      if (session.user.role === 'admin') return redirect('/admin');
      if (lastPath) return redirect(lastPath);
      return redirect('/preferences/workspace');
    } else {
      return redirect('/onboard');
    }
  }
  return <div className="">{children}</div>;
}
