import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (session?.user) {
    if (session.user.kbaVerified) {
      if (session.user.role === 'admin') return redirect('/admin');
      return redirect('/dashboard');
    }
  }
  return <div className="">{children}</div>;
}
